### ISSUE TITLE
Not authenticated :/

### ISSUE THREAD

**Issue by FukjemiCZ** [FAXES/tractive#1]
Hello, I have a problem with logging in. Could you advise me if it's necessary to enable access through the Tractive API first? It keeps showing me "Not authenticated." Can you also provide guidance on which variables I need to change for the initial login?
Thanks :)

**Comment by FAXES** [comment]
> Hello, I have a problem with logging in. Could you advise me if it's necessary to enable access through the Tractive API first? It keeps showing me "Not authenticated." Can you also provide guidance on which variables I need to change for the initial login? Thanks :)

Tractive doesn't have a proper API sadly, so the way of working around this is providing your standard login details to do what we do. So a username (account email) and its password are required.

**Comment by FAXES** [comment]
By using the `connect()` function you should have no issues being able to use other functions. The `connect()` function returns true when it logs in.
