### ISSUE TITLE
Tractive X Siri Shortcuts

### ISSUE THREAD

**Issue by itzamateama** [FAXES/tractive#2]
Hi! Thank you for sharing.
Unfortunatly I'm not a programer, I just play with Siri Shortcuts, and the other day I found your project and I was trying to make it work with Shortcuts to ask Siri where is my pet?, but I don't really know what I was doing, I don't know anything about Java.

The only thing I know is that you can run Java scripts on safari and on this way, use APIs like yours.

Here is what I was trying to do
https://www.reddit.com/r/shortcuts/comments/agh6ro/using_javascript_in_your_shortcuts/

So I was wondering if you don't mind, can you show me how to use your project?

Thank you again!

**Comment by FAXES** [comment]
Hi @itzamateama,

Shortcuts aren't something this package is intended for, this package is for Node.Js applications. Realistically these can be exported to work within HTML components. However, that's not the design I have here.

You could look into something like [Browserify](https://browserify.org) to do this with this package, but you'd also need the functions to be executed.

---

In honesty, it might be worth contacting Tractive support to make the feature request for Shortcut integrations as they'd be able to add to their application for this seamlessly. Tractive support is pretty good.

**Comment by itzamateama** [comment]
Hey! Thank you so much! Yes, I already talked with Tractive support (they’re really helpful), but sadly they said that there is not on their plans for now. But thank you again for your reply. Itzamatul Amaro ParedesEl oct 15, 2023, a la(s) 4:39 a.m., FAXES ***@***.***> escribió:Hi @itzamateama,
Shortcuts aren't something this package is intended for, this package is for Node.Js applications. Realistically these can be exported to work within HTML components. However, that's not the design I have here.
You could look into something like Browserify to do this with this package, but you'd also need the functions to be executed.

In honesty, it might be worth contacting Tractive support to make the feature request for Shortcut integrations as they'd be able to add to their application for this seamlessly. Tractive support is pretty good.
