### ISSUE TITLE
Is premium plan required to access location data via this API?

### ISSUE THREAD

**Issue by therealmattsims** [FAXES/tractive#5]
Hello, found your Tractive repo and wanted to ask before I got too far implementing it. At this point I'm mainly trying to get access to the map's location data (which expires every few days on the standard plan). Premium plan allows full history location data download, but it's expensive. 
Any knowledge you have on this appreciated.
Matt

**Comment by FAXES** [comment]
Yeah, you'd be correct this is a limitation by Tractive so there is not much that we can do via the available methods to get this data.

This isn't likely the news you wanted but it is what it is, hopefully, this has helped a bit for you @therealmattsims 🙂
